### ISSUE TITLE
Loss is summed over the batch to estimate the distance to the boundary

### ISSUE THREAD

**Issue by jeromerony** [pralab/Fast-Minimum-Norm-FMN-Attack#1]
Hi,

I was trying to implement this nice work into my adversarial library.
However, I noticed something odd in the code. When [estimating the distance to the boundary](https://github.com/maurapintor/Fast-Minimum-Norm-FMN-Attack/blob/6be936d6ab75a36aaa3d1c7233ce1f9c5e709d7e/src/attacks/fmn.py#L192), the loss is summed over all samples in the batch.
This means that the estimate is correct when attacking one sample, but largely overestimated when attacking a batch of samples.

For isntance, attacking one sample of MNIST provides a distance of 2.6314 in the first iteration but attacking two samples (with the same first), gives [5.5989, 5.8717]. This scales indefinitely; with 100 samples in the batch, the distances are: [201.1688, 210.9703, ...] in the first iteration.

**Comment by maurapintor** [comment]
Hi @jeromerony,
thanks for testing our code and congrats on your library, it is very good work! 
I will fix this bug as soon as possible, it is indeed a very nice catch!

**Comment by maurapintor** [comment]
Closed with #2.
